services:
  db:
    image: postgres:15
    container_name: library_db
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - library_postgres_data:/var/lib/postgresql/data
      - ./data/datasets:/datasets
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: library_backend
    restart: always
    ports:
      - "8000:8080"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: library
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      APPLICATION_SECURITY_JWT_SECRET_KEY: ${JWT_SECRET}

  frontend:
    build: ./frontend
    container_name: library_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      VITE_API_BASE_URL: http://localhost:8000
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html

volumes:
  library_postgres_data:
